# Generated by Django 5.2 on 2025-04-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='game_images/')),
            ],
        ),
    ]
